version: "3.1"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fullstack-challenge
    volumes:
      - ./data/postgresql:/var/lib/fullstack-challenge
